### ISSUE TITLE
ModuleNotFoundError: No module named 'ibmfl'

### ISSUE THREAD

**Issue by jiang121381** [IBM/federated-learning-lib#100]
How can i discuss the question in generate_data.py?

**Comment by Nathalie-B** [comment]
Hi @jiang121381 thanks for your interest in IBM FL, we have a slack channel where it may be easier to discuss questions.

We have set up a Slack channel for ongoing discussion. Join the IBM federated learning workspace: https://ibm-fl.slack.com/. If the previous link does not work for you, you can also use [this invitation link](https://join.slack.com/t/ibm-fl/shared_invite/zt-ff0k1xgh-IL9Aq6sW6rNny9gDdnEttQ). 

Feel free also to ask your question here.
