### ISSUE TITLE
AttributeError:   “Party”  object has no attribute "connection".

### ISSUE THREAD

**Issue by jiang121381** [IBM/federated-learning-lib#102]
It's in party.py  . I have tried to add the attribute "connection" to it.But it seems that it doedn't work.

**Comment by Yi-Zoey** [comment]
Hi @jiang121381 can you provide more details about when you encountered this issue? And can you also share your party's config file?

**Comment by jiang121381** [comment]
It happened when i run the project in "sklearn_logclassification_rw_p0.ipynb".
The code " File "examples/rw_p0.py", line 64, in <module>
    party_new.register_party(is_active=False)
"
File "/home/jiang/anaconda3/envs/ibmfl/lib/python3.6/site-packages/ibmfl/party/party.py", line 158, in register_party
    'connection': self.connection.get_connection_config(),
AttributeError: 'Party' object has no attribute 'connection'
And i have checked the party.py.There is no attribute "connection".the code is below:
        self.data_handler = None
        self.fl_model = None
        self.evidencia = None

Then i try to add the attribute "connection"to it.But it shows that "NonetypeError"

**Comment by Yi-Zoey** [comment]
@jiang121381 thanks for providing this information. We are working on fixing this notebook.

**Comment by jiang121381** [comment]
Thank you for your help!

**Comment by Yi-Zoey** [comment]
@jiang121381 if you pull from the current main, and run the new notebook, it should resolve the issue you've seen.
