### ISSUE TITLE
numpy: these package versions have conflicting dependencies. 

### ISSUE THREAD

**Issue by Yuchen-ck** [IBM/federated-learning-lib#112]
I ran the instruction:  pip install <IBM_federated_learning_whl_file>
But there are the errors, how to fix it?
ERROR: Cannot install federated-learning-lib and federated-learning-lib==1.0.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    federated-learning-lib 1.0.7 depends on numpy==1.17.4
    aif360 0.3.0 depends on numpy>=1.16
    gensim 3.8.3 depends on numpy>=1.11.3
    gym 0.19.0 depends on numpy>=1.18.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by Yuchen-ck** [comment]
![image](https://user-images.githubusercontent.com/79828908/186924805-02b8368c-745f-42d4-a914-5eeba0caf433.png)

**Comment by Yi-Zoey** [comment]
Hi @Yuchen-ck , which python version you are using? You can also refer to this issue #93.

**Comment by Yuchen-ck** [comment]
python=3.6 AND tensorflow=1.15， should i upgrade  TensorFlow to 2.1 version?

**Comment by Yi-Zoey** [comment]
I don't think this should be an issue, in our new version of WHL, we've removed the numpy version requirement.

**Comment by Yuchen-ck** [comment]
Thanks!
