### ISSUE TITLE
No module named ibmfl

### ISSUE THREAD

**Issue by gauravkumar411** [IBM/federated-learning-lib#14]
I am unable to find the **ibmfl** module in the code repository and hence being unable to run and test the framework. Could you please help me with this.
Would appreciate your help in resolving this issue.
Thanks.

**Comment by shashank215r** [comment]
@gauravkumar411 
The current release of `ibmfl` is closed source, we are working on open-sourcing the code so until then you won't find `ibmfl` in PyPI repositories. For now we included the whl file in `federated-learning-lib` folder which can be installed using 
`pip install federated_learning_lib-1.0-py3-none-any.whl`

Please use this [quickstart](https://github.com/IBM/federated-learning-lib/blob/main/quickstart.md) tutorial  to setup `ibmfl` environment.
