### ISSUE TITLE
ibmfl doesn‘t include 'KrumFusionHandler'

### ISSUE THREAD

**Issue by EmmetWilliam** [IBM/federated-learning-lib#17]
I was about to run 'python -m ibmfl.aggregator.aggregator <krum_agg_config>', however find the module doesn't even include the relevant fusion file.  Could you please help me with this.
Would appreciate your help in resolving this issue.
Thanks.

**Comment by heikoludwig** [comment]
Hi, thanks for trying out IBM FL. It turns our we actually missed it when putting together the WHL. Thanks so much for finding this. We'll fix it and get back to you.

**Comment by shashank215r** [comment]
Thanks @EmmetWilliam for pointing this out. We apologize for missing out this algorithm in the WHL file. We’ve updated the WHL with krum fusion handler and packaged a new release with version [v1.0.1](https://github.com/IBM/federated-learning-lib/releases/tag/v1.0.1). Please try out the new release and let us know if you have any questions.
