### ISSUE TITLE
Can not find the appropriate version of Ray

### ISSUE THREAD

**Issue by D-coder22** [IBM/federated-learning-lib#23]
![image](https://user-images.githubusercontent.com/43219702/94369691-0aa74580-0109-11eb-8dab-b3c2cc8c7b83.png)

While installing the wheel file, I've been facing this issue. I've tried to find a solution but can not seem to find any, could any of you help me with this issue?

**Comment by shashank215r** [comment]
Hey @D-coder22  Thank you for your interest in IBM federated-learning-lib !

Seems like you are using a windows machine, and unfortunately `ray` is only supported on linux and mac. In federated-learning-lib only RL models depends on this library and if you are interested in using other models, one workaround is to install `federated-learning-lib` without the dependencies using `--no-deps` flag and later install all required libraries.

Here is the list of libraries you may need for other models.

tensorflow==1.13.1
scikit-learn==0.22.2post1
keras==2.2.4
numpy==1.17.4
pandas
pytest
PyYAML
parse
Flask
jsonpickle
requests
scipy
environs
pathlib2
diffprivlib
psutil
setproctitle
tabulate
lz4
opencv-python
gym
cloudpickle==1.3.0

**Comment by D-coder22** [comment]
@shashank215r Thank you very much for your help!
