### ISSUE TITLE
i don't understand! where should i setup keras code ? :/

### ISSUE THREAD

**Issue by lezandto** [IBM/federated-learning-lib#25]

**Comment by Yi-Zoey** [comment]
Hi, thank you for trying out IBM FL. We have a [quickstart page](https://github.com/IBM/federated-learning-lib/blob/main/quickstart.md) to provide you guidance to set up the IBM FL library and then try out our Keras CNN example. Once you set up the conda environment and activate it, you can run the code to generate data and configuration files in the directory where the `examples` folder is located. It should be the `federated-learning-lib` folder. 
If you want to train your own Keras model, please modify the code inside `get_model_config()` method in [keras_classifier](https://github.com/IBM/federated-learning-lib/blob/main/examples/keras_classifier/generate_configs.py#L60) and provide a new data handler to load and preprocess data if necessary. You can find the related tutorials in https://github.com/IBM/federated-learning-lib/tree/main/docs/tutorials.

**Comment by Nathalie-B** [comment]
@lezandto You need to specify and save the model as an `h5` and provide a pointer to the stored file in the `yml` configs. Hope this helps!
