### ISSUE TITLE
Connection issues between an aggregator and a party on separate systems (same OS - win10)

### ISSUE THREAD

**Issue by limacwin** [IBM/federated-learning-lib#29]
I have been trying to train the **IBM FL Keras MNIST example** using 2 laptops: one as an aggregator and the other as a party, but started facing issues pertaining to the IP address specification in their respective config.yml files. Have uploaded the image files for reference. (I've used a Flask connection and a server).
![config_agg](https://user-images.githubusercontent.com/67916802/95258938-0f27d880-0844-11eb-8ad8-3ec54cdd35c6.png)
![config_party](https://user-images.githubusercontent.com/67916802/95258944-10f19c00-0844-11eb-9554-0dc49a2da0c5.png)
When the aggregator and the party was initialized and registered, the connection wasn't getting through and there arose a registration error on the party terminal. 

**Would just like to know as to where I've gone wrong or if there's a possible fix/alternative method for the above stated problem.**

**Please revert back as soon as possible**

Thank You!

**Comment by chalianwar** [comment]
Hi, thank you for trying out IBM FL. The configuration settings look correct. Could you please share the detail output from both Aggregator and Party side. Also, please make sure there is no firewall issues and you able to ping both machines.

**Comment by limacwin** [comment]
Thank you for responding! Below attached are the snips of the aggregator and party terminals. (aggregator: PC1, party: PC2)

After generating the configuration files, we did the following things: 

First, we ran the aggregator .yml file, after which we started the aggregator, opening it to accept and send queries: 

![aggregator](https://user-images.githubusercontent.com/67916802/95376241-6f7b5080-08fe-11eb-8f2a-29946c0ad61e.png)

(The above terminal was launched in PC1)

Then, on PC2, we ran the party .yml file: 

![party_snip1](https://user-images.githubusercontent.com/67916802/95376403-aa7d8400-08fe-11eb-91ea-659e4f7fff5f.PNG)

After starting the party and then registering it to the aggregator, the following errors started popping up: 

![party_snip2](https://user-images.githubusercontent.com/67916802/95376719-27a8f900-08ff-11eb-8b54-0910db2c1e7f.PNG)

![party_snip3](https://user-images.githubusercontent.com/67916802/95376887-63dc5980-08ff-11eb-9105-2e162de04300.PNG)

![party_snip4](https://user-images.githubusercontent.com/67916802/95376894-65a61d00-08ff-11eb-9f43-98b621387f63.PNG)

![party_snip5](https://user-images.githubusercontent.com/67916802/95376897-663eb380-08ff-11eb-8571-3ac7fa8285bd.PNG)

We checked the firewall settings as well, and we didn't encounter any related/necessary service which appeared to be blocked.

**Looking at the above attached snips, do let me know if the errors are on my side and if I should rectify or carry out anything in some other manner.**
**Thank You.**

**Comment by chalianwar** [comment]
Could you please try following:
1) Try to telnet Aggregator server from the party machine `telnet 192.168.0.104 5000`. If you are unable to connect then you need to fix network settings to allow access to this ip and port.
2) You can also try setting Aggregator ip to 0.0.0.0 only in the Aggregator config. Please keep aggregator ip to 192.168.0.104 in the party config file.

**Comment by limacwin** [comment]
Okay. Thank you for the reply! Will try it out and get back over here soon!

**Comment by shashank215r** [comment]
Did this fix your issue @limacwin ?

**Comment by limacwin** [comment]
Sorry for the late reply, we ended up using Docker to resolve the above issue that we were facing and we were able to establish a secure connection, allowing the aggregator PC and the party PCs to communicate with each other, successfully training the model in the end. Thank you for your help!
