### ISSUE TITLE
How to Add Custom Data Handlers and Support A New Keras Image Classifier?  

### ISSUE THREAD

**Issue by amogh-tarcar** [IBM/federated-learning-lib#3]
I was looking for a way to define a new Keras Image classifier which supports Images which have 3 channels and 224px resolution(3,224,244) . 

I tried adding a new config file : similar to "examples/keras_classifier/generate_configs.py" with some changes ; however there is a dependency for "ibmfl.util.data_handlers.mnist_keras_data_handler".  How should I go about adding a new data hander ? 

`def get_datahandler_config(dh_name, folder_data, party_id, is_agg):
    if dh_name == 'mnist':
        data = {
            'name': 'MnistKerasDataHandler',
            'path': 'ibmfl.util.data_handlers.mnist_keras_data_handler',
            'info': {
                'npz_file': os.path.join(folder_data, 'data_party' + str(party_id) + '.npz')
            }
        }
        if is_agg:
            data['info'] = {
                'npz_file': os.path.join("examples", "datasets", "mnist.npz")
            }`

**Comment by shashank215r** [comment]
You can extend the `DataHandler` class with your own implementation say CustomDataHandler. 

- Modify the  `__init__` method to load the dataset information(such as file_name) via data_config. The argument `data_config` in `__init__` method is passed down from datahandler config of yml file. 

- Modify `get_data` method to load your data and pre-process it as per your usecase and return the data in (x_train, y_train), (x_test, y_test) format. Most of the fl modules expect the data in this format for training and evaluation.

- Once the datahandler is ready, test it by updating config yml with CustomDataHandler path and running one training iteration.

```python

# imports from ibmfl lib
from ibmfl.data.data_handler import DataHandler

class CustomDataHandler(DataHandler):

    """
    Data handler for your dataset.
    """
    def __init__(self, data_config=None, channels_first=False):
        super().__init__()
        self.file_name = None
        if data_config:
            if 'your_data_file' in data_config:
                self.file_name = data_config['your_data_file']

    def get_data(self):
        """
        Gets pre-process training and testing data. 
        :return: ((x_train, y_train), (x_test, y_test)) # most build-in training modules expect data in this format
        :rtype: `tuple`
        """
        pass


```

**Comment by shashank215r** [comment]
https://github.com/IBM/federated-learning-lib/blob/main/docs/tutorials/create_my_data_handler.md
Link to our custom datahandler tutorial.

**Comment by amogh-tarcar** [comment]
> https://github.com/IBM/federated-learning-lib/blob/main/docs/tutorials/create_my_data_handler.md
> Link to our custom datahandler tutorial.

Thank you so much. This detailed tutorial is great for masking custom data handler.
