### ISSUE TITLE
No model found for Pytorch in IBMFL

### ISSUE THREAD

**Issue by D-coder22** [IBM/federated-learning-lib#30]
Been working on a project with IBMFL, but was wondering about the support it provides for Pytorch. I wanted to use Pytorch to build a CNN rather than keras, is there any way you can help me with regard this?

**Comment by Nathalie-B** [comment]
Hi @D-coder22 thanks for reaching out. We haven't put out our implementation for Pytorch yet. This is something we are considering publishing in our next release.

**Comment by D-coder22** [comment]
Alright, Thank you
