### ISSUE TITLE
How to run experiments on multiple GPUs environment using ibmfl package?

### ISSUE THREAD

**Issue by moFang222** [IBM/federated-learning-lib#34]
Hi. Follow the tutorial, I can run the program under the cpu environment. 
But how can I run the program under the gpu environment? Is it simply done by installing the tensorflow-gpu or does it need other setup? 
Many thanks!

**Comment by Yi-Zoey** [comment]
Hi, thanks for reaching out! If you want to train a Keras model with only 1 GPU, you can just install the corresponding tensorflow-gpu package. We will be supporting multiple GPUs in our coming release. Stay tuned!

**Comment by Yi-Zoey** [comment]
Hi, please check out our [new release](https://github.com/IBM/federated-learning-lib/releases/tag/1.0.2) with multiple GPU support and the corresponding tutorial for [configure gpu training](https://github.com/IBM/federated-learning-lib/blob/main/docs/tutorials/configure_gpu_training.md).

**Comment by saigontrade88** [comment]
Hi, for pytorch models, using single-process DataParallel with multiple GPUs is slow. Pytorch does suggest using DistributedDataParallel for multiple GPU training in this [link](https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html#torch.nn.DataParallel). Can you suggest how to implement multiple GPU training? Many thanks.
