### ISSUE TITLE
How use sklearn k means model?

### ISSUE THREAD

**Issue by ElsaBroso1** [IBM/federated-learning-lib#48]
Hi!

I am trying to use a sklearn k means model, so in the party's aggregator when I am in the model part I saw the documentation but in the part of models in sklearn k means wrapper there is  ibmfl.connection.flask_connection.FlaskConnection. It should be something like ibmfl.model.sklearnkmeans, isn't it?

Thanks in advance

**Comment by Nathalie-B** [comment]
Hi Elsa,
The following example generates the `yml` files to train a k-means model:  https://github.com/IBM/federated-learning-lib/blob/main/examples/spahm/generate_configs.py
As you can see you will need to use `SPAHMFusionHandler` 

You can run the example following this readme: 
https://github.com/IBM/federated-learning-lib/tree/main/examples/spahm

**Comment by ElsaBroso1** [comment]
Thank you! I completely forgot about that files. I hope it works now.
