### ISSUE TITLE
Problem with printing graphics with sklearn_logclassification

### ISSUE THREAD

**Issue by Enrique-Marmol** [IBM/federated-learning-lib#50]
Hello everyone,
I was running the sklearn_logclassification model with a dataset of mine. The model runned successfully, but when I wanted to plot the graphics as the keras clasiffier the variables eval_party_accuracy and iterations are empty.
![imagen](https://user-images.githubusercontent.com/75251123/104916058-d4c8ee00-5991-11eb-8b22-5652cc1dc6b3.png)
![imagen](https://user-images.githubusercontent.com/75251123/104917570-ddbabf00-5993-11eb-8bc7-47a7d9e2d709.png)

I named agg_config as agg, and as in sklearn_logclassification there is not epochs so I wrote max iter. I tried to seek the problem, but I could not find anythig. How do I have to change the code to make it work for a sklearn_logclassification model? 
Thanks in advance

**Comment by shashank215r** [comment]
@Enrique-Marmol 
The approach you used here is correct, to confirm if the configuration changes are on point for this approach,
Could you paste the hyper parameters you are using for this training run(Just the hyperparams section of the config).
Also try printing `eval_party_accuracy` and `iterations` at the start of **cell 8** to see what is being saved every round.

**Comment by Enrique-Marmol** [comment]
These are my hyperparams:
```
hyperparams:
  global:
    parties: 2
    rounds: 3
    termination_accuracy: 0.9
  local:
    training:
      max_iter: 2
```

When I printed `eval_party_accuracy` and `iterations` they are empty, `[[],[]]`. So I decided to debug the program, and what I could find is that the variable that save the metrics, in sklearn model is empty, but in keras are filled. I mean, in keras we have 
![imagen](https://user-images.githubusercontent.com/75251123/105490099-947caf00-5cb4-11eb-869d-9d9e9388b8f5.png)
However, in sklearn  I have
![imagen](https://user-images.githubusercontent.com/75251123/105490357-f0473800-5cb4-11eb-873e-e6a14778cc1e.png)
This is what I could achieve at the moment.

**Comment by shashank215r** [comment]
@Enrique-Marmol
Could you share the notebooks you are using for this test, the approach seems to be fine here and it should give you the evaluations on aggregator side. Let me check your notebook files and see if there is anything fishy going on there.

To speed things up, how about we continue this discussion in https://ibm-fl.slack.com/  ?

**Comment by shashank215r** [comment]
Seems like parties are running in private mode.
Adding the below line in party notebook after party registration would fix the issue.
```
party.proto_handler.is_private = False  ## allows sharing of metrics with aggregator
