### ISSUE TITLE
Is is possible to implement a new ML algorithm?

### ISSUE THREAD

**Issue by pablofs20** [IBM/federated-learning-lib#54]
Hello,

As the title says, I was wondering if could be possible to implement a new type of algorithm in addition to the default ones. I have successfully integrated my own dataset using the sklearn_logclassification algorithm, but I expect that a Random Forest classifier would perform better for my case, and it's not included in here. Would be possible to integrate it? If it is, what steps should I take? Or should I wait for an updated version of the library that comes with it?

Thanks!

**Comment by Yi-Zoey** [comment]
Hi, thanks for using IBM FL Library. We have created this repository(https://github.com/ibm/federated-learning) with the MIT license for users to add their customized fusion algorithms, models, and more. We are working on adding instructions, tutorials, and codes to facilitate the process. Stay tuned!

**Comment by heikoludwig** [comment]
There's API documentation that explains the classes  you have to extend: [ http://ibmfl-api-docs.mybluemix.net/index.html  ]( http://ibmfl-api-docs.mybluemix.net/index.html  )

For your project, this will probably be a local training handler to perform your party-local work and a fusion handler for what you want to do in the aggregator. There are many options where to grow trees and how to put them together. The docs @Yi-Zoey  is mentioning should help but don't hesitate to ask more questions.

**Comment by Yi-Zoey** [comment]
We have added a [new tutorial](https://github.com/IBM/federated-learning-lib/blob/main/docs/tutorials/add_a_new_fl_algorithm.md) to discuss this topic.
