### ISSUE TITLE
Failed to SAVE the model

### ISSUE THREAD

**Issue by yusx-swapp** [IBM/federated-learning-lib#59]
When I run the SAVE in Keras backend, it works well. However, when in Pytorch backend, it was failed to save the party model.

here is the information:
anaconda3/envs/fl/lib/python3.6/site-packages/ibmfl/party/training/local_training_handler.py", line 87, in save_model
    self.fl_model.save_model()
TypeError: save_model() missing 1 required positional argument: 'model_filename'
![image](https://user-images.githubusercontent.com/78742415/115907143-0c689a00-a49b-11eb-8f4a-92d44fcbed9f.png)

**Comment by shashank215r** [comment]
@yusx-swapp 
Thanks for checking out IBMFL.
This error appeared due a bug in Pytorch model. We will be quickly releasing a new lib to fix this issue.
