### ISSUE TITLE
How should I configure warm start mode?

### ISSUE THREAD

**Issue by pablofs20** [IBM/federated-learning-lib#60]
Hi!

I'm tweaking some configuration parameters in the framework to see how the test results variate. After trying to switch on the warm start mode, I get an error indicating that no initial model has been provided. How can I pass this initial model to the framework? I've thought of creating it externally, serializing it in a .pickle file and indicating it somehow in the configuration files, but I'm not sure about this. Also, should the model met some requirements? I'm lost on this, would appreciate some kind of help.

Thank you!

**Comment by Yi-Zoey** [comment]
Hi Thanks for trying out IBM FL. It seems like you are using Sklearn linear models? Can you provide more details about the model type and fusion algorithms you are using for warm start?

**Comment by pablofs20** [comment]
Hi, I'm using the default one in the sklearn_logclassification folder (sklearn's SGDclassifier) and IterAvg fusion algorithm (also, the default one). I didn't try creating a model for warm start, since I don't know how to provide it to the framework.

**Comment by shashank215r** [comment]
@pablofs20 
Could you share the error you are getting when you provide the model ?
For warm start to work, the model should be pre-trained. The model we generate through examples is not pre-trained and does not contain weights. Try training a round or two with the model and use it as initial model on aggregator.

**Comment by pablofs20** [comment]
But my main question is: how do I provide that pre-trained model to the framework? Do I have to save it into a pickle file (using a external script)? Is there a directive in the aggregator configuration file to specify the path to this file? I didn't find any information on how to do that. Thanks.

**Comment by shashank215r** [comment]
Try adding model config on aggregator config yaml files. Copy the model section from party and put it in aggregator yaml file.
`model:`
 ` name: SklearnSGDFLModel`
  `path: ibmfl.model.sklearn_SGD_linear_fl_model`
`  spec:`
   ` model_definition: examples/configs/iter_avg/sklearn/model_architecture.pickle`

**Comment by pablofs20** [comment]
Including the model section into aggregator's yaml file and launching the experiment, I got an error indicating that model was not fitted. What I tried then is fitting the model externally using a script and the data from one of the parties, saving it into a .pickle file and providing the new path to the file into the yaml. Now, it seems that the frameworks detects that model is correctly fitted, the process starts successfully (with warm start) but as soon as one client receives the pre-initialized model and asks for the coef_ attribute to perform the aggregation to generate the model update, it raises an AttributeError indicating that coef_ attribute doesn't exist. How can this be posssible? I have checked that coef_ attribute is available after calling to fit in my external script, but seems like it disappears when the model is serialized using pickle.

Any thoughts on this?

**Comment by pablofs20** [comment]
Sure, this is the code from the external script I've used to generate the pre-trained model:

```
import pandas as pd
import numpy as np
import os
import joblib
from sklearn.linear_model import SGDClassifier


df = pd.read_csv("data_party1.csv")

x_0 = df.iloc[:, :-1]
y_0 = df.iloc[:, -1]

x_train = np.array(x_0)
y_train = np.array(y_0)

model = SGDClassifier(loss='log')

model.fit(x_train, y_train)

fname = "initial_model.pickle"

with open(fname, 'wb') as f:
    joblib.dump(model, f)
```

And this is the content of aggregator's config file:

```
connection:
  info:
    ip: 127.0.0.1
    port: 5000
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    txt_file: examples/datasets/adult.data
  name: AdultSklearnDataHandler
  path: ibmfl.util.data_handlers.adult_sklearn_data_handler
fusion:
  name: IterAvgFusionHandler
  path: ibmfl.aggregator.fusion.iter_avg_fusion_handler
hyperparams:
  global:
    parties: 2
    rounds: 10
    termination_accuracy: 0.9
  local:
    training:
      max_iter: 2
model:
  name: SklearnSGDFLModel
  path: ibmfl.model.sklearn_SGD_linear_fl_model
  spec:
    model_definition: examples/configs/sklearn_logclassification/initial_model.pickle
protocol_handler:
  name: ProtoHandler
  path: ibmfl.aggregator.protohandler.proto_handler
```

**Comment by Yi-Zoey** [comment]
I followed the same way to produce an initial model using MNIST but I can't reproduce the error you've mentioned above. For faster communication, do you mind joining our general slack channel: https://ibm-fl.slack.com/ so I can help to resolve the issue?

**Comment by pablofs20** [comment]
Should I receive an invitation to join? I'm not able to access.
