### ISSUE TITLE
🚨 Potential Code Injection (CWE-94)

### ISSUE THREAD

**Issue by huntr-helper** [IBM/federated-learning-lib#66]
👋 Hello, @Yi-Zoey, @shashank215r, @heikoludwig - a potential critical severity Code Injection (CWE-94) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-IBM/federated-learning-lib** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by huntr-helper** [comment]
📦 A patch has been submitted for this report. 🔗 Check the patch (https://github.com/IBM/federated-learning-lib/compare/HEAD...b3ef:main) or visit the advisory page (https://huntr.dev/bounties/1-other-IBM/federated-learning-lib) for more information.

**Comment by heikoludwig** [comment]
Bot

**Comment by JamieSlome** [comment]
@heikoludwig - was this vulnerability invalid?
