### ISSUE TITLE
RabbitMQ - documentation refinement

### ISSUE THREAD

**Issue by koen-ongena-imec** [IBM/federated-learning-lib#87]
I'm trying to use RabbitMQ as a connection.

The documentation (`setup.md` - paragraph "Create Configuration Files") lists some steps to generate configs for RabbitMQ connections.
However, it is unclear to me what is meant by `'rabbit' : {from the IBM team}}` in the `IBMFL_BROKER` variable. Can you provide a sample of that `{from the IBM team}`. What should I fill in there when trying to connect to a locally installed RabbitMQ?

**Comment by mkepurcell** [comment]
This feature is still under development and not yet fully implemented.

**Comment by koen-ongena-imec** [comment]
OK, thank you for the clarification.

**Comment by mkpurcell** [comment]
This feature is now available in the latest release v1.0.7.
