### ISSUE TITLE
Hierarchical architecture for agg and parties in IBM FL framework

### ISSUE THREAD

**Issue by mf-smh** [IBM/federated-learning-lib#88]
Hello,
happy new year
I`m started using IBM FL framework for a while and i want to use it for my thesis project and i have some questions in this regard and I would be grateful if you could help me.
 
1-Is it possible to consider a hierarchical architecture, for example three or more layer of aggregator and parties in IBM FL framework?If yes,how?
2-Is it possible to add energy or other related fields for parties and aggregator?
3-Is it possible to add other metrics than accuracy for evaluation in IBM FL, like latency, energy or bandwidth usage?
4-Do the parties have the same configuration or are they heterogeneous at the beginning of the local training?

Thanks so much

**Comment by chalianwar** [comment]
For 1 to 3, these features are not implemented and currently out of the scope for the CE.
4) Yes, generate config script generates mostly the same config for all clients, excluding ports etc.
