### ISSUE TITLE
Can not build an image from Dockerfile 

### ISSUE THREAD

**Issue by iazpiroz** [IBM/federated-learning-lib#97]
I try to build an image with the Dockerfile, but I obtain the following error:

> executor failed running [/bin/sh -c pip3 install -q -r requirements.txt]: exit code: 1
>...
> #15 123.1   gensim/similarities/fastss.c:725:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
>#15 123.1            for (WIDTH tmpi = 0; tmpi <= len_s1; tmpi++) row2[tmpi] = tmpi;
>#15 123.1     error: command 'gcc' failed with exit status 1
> ...
>#15 207.1 ERROR: Command errored out with exit status 1: /opt/app-root/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1vc_lczh/gensim_f69d10d382ee4212ba76a739189d3808/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1vc_lczh/gensim_f69d10d382ee4212ba76a739189d3808/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l0z1vmfl/install-record.txt --single-version-externally-managed --compile --install-headers /opt/app-root/include/site/python3.6/gensim Check the logs for full command output.

Could you update the requirements file to build a docker image?
Thank you in advance.

**Comment by chalianwar** [comment]
Thanks for trying IBMFL. Could you please try following change to install gensim==3.8.3 version. It should fix the docker build.

`diff --git a/requirements.txt b/requirements.txt
index 427f8fe..c32a43a 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -26,7 +26,7 @@ h5py==2.10.0
 image
 aif360
 fairlearn
-gensim
+gensim==3.8.3
 ray
 dm-tree
 GPUtil`

**Comment by chalianwar** [comment]
We fixed it in main repo.

**Comment by iazpiroz** [comment]
Many thanks @chalianwar !
