### ISSUE TITLE
Notebook Training Scikit-Learn models in IBM FL no accesible

### ISSUE THREAD

**Issue by iazpiroz** [IBM/federated-learning-lib#98]
Hi everybody,
The first two examples (SGDClassifier, and Logistic Classifier) are not correctly linked or are not accessible through the links available in the documentation of [Github Tutorials](https://ibmfl.mybluemix.net/tutorials).

**Comment by Yi-Zoey** [comment]
Hi @iazpiroz, thanks for pointing it out! We will update those links on our website soon. At the same time, if you would like to try out those examples, you can find examples for scikit-learn models in [here](https://github.com/IBM/federated-learning-lib/tree/main/examples/iter_avg), and also [here](https://github.com/IBM/federated-learning-lib/tree/main/Notebooks/sklearn_logclassification_rw).

**Comment by iazpiroz** [comment]
Many thanks @Yi-Zoey!

**Comment by Yi-Zoey** [comment]
We have updated the links on [our website](https://ibmfl.mybluemix.net/).
